### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dugengmaster** [whats2000/CodeBRT#2]
1. 將CodeBRT向左慢慢水平拉伸來隱藏CodeBRT介面時，於特定width開始輸入框會開始逐漸提高height。建議讓輸入框改成固定height，這樣能讓水平拉伸到最小來隱藏CodeBRT時看起來更滑順。

3. 漢堡菜單會遮擋住Chat History跟General Settings和Voice Settings的設定介面。

**Comment by whats2000** [comment]
Never mind I will update it

**Comment by whats2000** [comment]
I will adjust the layout to test have better effect

**Comment by whats2000** [comment]
Here you go 3525cfe0277875429804185270283f6679366dd8

**Comment by whats2000** [comment]
The new beta file will auto-generate on the [here](https://github.com/whats2000/CodeBRT/actions/runs/10239876290)
