### ISSUE TITLE
[Feature Request] Add Conversation Termination

### ISSUE THREAD

**Issue by dugengmaster** [whats2000/CodeBRT#3]
### **Description:**

**Feature Request:**

I would like to request the addition of a "conversation termination" feature to the CodeBRT plugin. This feature would allow users to instantly stop the AI's response generation at any point during the interaction, similar to how ChatGPT allows users to terminate a conversation at any time.

**Use Case:**

This feature would be particularly useful in situations where the AI is generating a response that is no longer needed or relevant, saving time and improving user experience. It can also help prevent long and unnecessary processing when the user has already found the desired solution.

**Expected Outcome:**

- A button or command to terminate the current AI response.
- Immediate stopping of the AI's processing and clearing of any ongoing response generation.

**Additional Considerations:**

- This feature should be easily accessible and intuitive, ideally integrated into the existing UI without adding complexity.
- Consider providing a confirmation prompt to avoid accidental termination, or allowing the user to configure this behavior in settings.

**Example:**
![stop buttom](https://github.com/user-attachments/assets/9c54b356-3564-4995-96d2-dd6d8e87bfa8)

**Comment by whats2000** [comment]
Yes, this has been placed in the queue backlog with position 2nd. I will soon start fixing it

**Comment by whats2000** [comment]
The termination had been done! 

https://github.com/whats2000/CodeBRT/commit/9cac0fdd1a29872be0c636e3bb07518c8e7bfd69
