### ISSUE TITLE
[Feature Request] Disable Auto-Scroll on Upward Scroll in Dialogue Box

### ISSUE THREAD

**Issue by dugengmaster** [whats2000/CodeBRT#4]
Description:
I would like to request a feature that disables auto-scrolling to the bottom of a dynamically generated dialogue box when the mouse wheel is scrolled upward. This will allow me to read the text without having to wait for all the content to load.

Expected Behavior:
When the user scrolls upward in the dialogue box, the auto-scroll to the bottom should be temporarily disabled, allowing the user to review previous content. Auto-scrolling can be re-enabled if the user scrolls back to the bottom or performs some other action.

Actual Behavior:
Currently, the dialogue box automatically scrolls to the bottom as new content is added, making it difficult to review previous content without waiting for the entire dialogue to finish.

Technical Details:
This could be achieved by adding an event listener that detects upward scroll events within the dialogue box and then temporarily disables the auto-scroll functionality.

Additional Context:
This feature would enhance user experience, particularly in long conversations or when reviewing important details from previous parts of the dialogue.

**Comment by whats2000** [comment]
Yes, this will be patch soon. The feature request is in progress

**Comment by whats2000** [comment]
https://github.com/whats2000/CodeBRT/commit/6524935666dac100bb403931327516817eda6113

**Comment by dugengmaster** [comment]
### Description:
The `disables auto-scrolling to the bottom` feature seems to be malfunctioning. When this option is enabled or disabled, the window still automatically scrolls to the bottom.

#### Steps to Reproduce:
1. Open the output panel or chat window in the application.
2. Try entering or loading a large amount of content.

#### Expected Behavior:
The window should remain at the current scroll position without automatically jumping to the bottom.

#### Actual Behavior:
The window automatically scrolls to the bottom.
---

### Environment:
- **Operating System**: Windows 10
- **Application Version**: 0.4.1
