### ISSUE TITLE
Ollama problem

### ISSUE THREAD

**Issue by EricYang801** [whats2000/CodeBRT#5]
Ollama沒辦法正確回應

**Comment by whats2000** [comment]
Here you go https://github.com/whats2000/CodeBRT/commit/77fad5c75b79c40ebb5d9205bc884b040803d107

**Comment by whats2000** [comment]
@EricYang801 
I think I fixed it, please feed back if it work :)
[code-brt-0.2.1+e669388.vsix.zip](https://github.com/user-attachments/files/16978409/code-brt-0.2.1%2Be669388.vsix.zip)

**Comment by EricYang801** [comment]
@whats2000 
Thx, Ok I will test it in the near  future.
