### ISSUE TITLE
disables auto-scrolling to the bottom functionality not working

### ISSUE THREAD

**Issue by dugengmaster** [whats2000/CodeBRT#8]
### Description:
The `disables auto-scrolling to the bottom` feature seems to be malfunctioning. When this option is enabled or disabled, the window still automatically scrolls to the bottom.

#### Steps to Reproduce:
1. Open the output panel or chat window in the application.
2. Try entering or loading a large amount of content.

#### Expected Behavior:
The window should remain at the current scroll position without automatically jumping to the bottom.

#### Actual Behavior:
The window automatically scrolls to the bottom.
---

### Environment:
- **Operating System**: Windows 10
- **Application Version**: 0.4.1

**Comment by whats2000** [comment]
The disables behavior current only triggers when the user is not at the bottom. This will cost a lot of time to investigate as this has been tried to fix 4 times. I also looking for help if someone can solve it. Reference current implementation https://github.com/whats2000/CodeBRT/blob/main/VSCodeExtension/code-brt/src/views/components/ChatActivityBar/MessagesContainer.tsx

**Comment by whats2000** [comment]
![image](https://github.com/user-attachments/assets/b6a8b852-3158-454e-a37f-738b0ef1abf4)
This shows why I have no idea what happened. This attribute from the package set to false will still trigger scroll.

**Comment by whats2000** [comment]
Alright, I think I might figure out how to fix it but it will disable the scrolling animation. Which make the bubble shaking

**Comment by whats2000** [comment]
Alright, I think I might figure out how to fix it but it will disable the scrolling animation. Which makes the bubble shaking
