### ISSUE TITLE
Excessive Process Creation When Using Agent Tool via CMD in CodeBRT

### ISSUE THREAD

**Issue by dugengmaster** [whats2000/CodeBRT#9]
Description:
When using the Agent tool in CodeBRT through the command line (CMD), it creates an excessive number of processes. 

Steps to Reproduce:
Open CMD and navigate to the directory containing the Agent tool.
Run the desired command using the Agent tool.
Observe the number of processes spawned by the tool.
Expected Behavior:
The Agent tool should manage its processes efficiently, spawning only single processes required for the operation.

Actual Behavior:
The tool spawns an excessive number of processes.

Environment:
Tool Name: CodeBRT Agent Tool
Operating System: Windows 10
CodeBRT Version: 0.4.1

[cfdde29c-fa63-4bf0-a33c-08757d20a00f.json](https://github.com/user-attachments/files/17899577/cfdde29c-fa63-4bf0-a33c-08757d20a00f.json)
![螢幕擷取畫面 2024-11-25 161318](https://github.com/user-attachments/assets/074f3042-6938-44b4-ae17-01fc069a3a96)

**Comment by whats2000** [comment]
Sound strange, I will take a look at it

**Comment by whats2000** [comment]
@dugengmaster Do you check the execution directory? The terminal might be in a different directory workspace. This happens when you use the `cd` command in the terminal. It will break the integrations!

**Comment by dugengmaster** [comment]
You’re absolutely right! I was indeed calling it from the parent directory. Thanks for pointing that out! 😊

**Comment by whats2000** [comment]
Umm, a quick note is that we separate the process when it run at different dir. Because this allow the Agent to debug a front-end and back-end separation system. It is ok if you close the unused terminal. The cd command will make more wrong behavior with the Agent, so we currently disable it.

**Comment by whats2000** [comment]
Umm, a quick note is that we separate the process when it run at different dir. Because this allow the Agent to debug a front-end and back-end separation system. It is ok if you close the unused terminal. The cd command will make more wrong behavior with the Agent, so we currently disable it.
